// Generated by gencpp from file teeterbot_gazebo/NudgeTeeterbot.msg
// DO NOT EDIT!


#ifndef TEETERBOT_GAZEBO_MESSAGE_NUDGETEETERBOT_H
#define TEETERBOT_GAZEBO_MESSAGE_NUDGETEETERBOT_H

#include <ros/service_traits.h>


#include <teeterbot_gazebo/NudgeTeeterbotRequest.h>
#include <teeterbot_gazebo/NudgeTeeterbotResponse.h>


namespace teeterbot_gazebo
{

struct NudgeTeeterbot
{

typedef NudgeTeeterbotRequest Request;
typedef NudgeTeeterbotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NudgeTeeterbot
} // namespace teeterbot_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::teeterbot_gazebo::NudgeTeeterbot > {
  static const char* value()
  {
    return "796f52ca95c2168aa4980dc41c6edf7e";
  }

  static const char* value(const ::teeterbot_gazebo::NudgeTeeterbot&) { return value(); }
};

template<>
struct DataType< ::teeterbot_gazebo::NudgeTeeterbot > {
  static const char* value()
  {
    return "teeterbot_gazebo/NudgeTeeterbot";
  }

  static const char* value(const ::teeterbot_gazebo::NudgeTeeterbot&) { return value(); }
};


// service_traits::MD5Sum< ::teeterbot_gazebo::NudgeTeeterbotRequest> should match 
// service_traits::MD5Sum< ::teeterbot_gazebo::NudgeTeeterbot > 
template<>
struct MD5Sum< ::teeterbot_gazebo::NudgeTeeterbotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::teeterbot_gazebo::NudgeTeeterbot >::value();
  }
  static const char* value(const ::teeterbot_gazebo::NudgeTeeterbotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::teeterbot_gazebo::NudgeTeeterbotRequest> should match 
// service_traits::DataType< ::teeterbot_gazebo::NudgeTeeterbot > 
template<>
struct DataType< ::teeterbot_gazebo::NudgeTeeterbotRequest>
{
  static const char* value()
  {
    return DataType< ::teeterbot_gazebo::NudgeTeeterbot >::value();
  }
  static const char* value(const ::teeterbot_gazebo::NudgeTeeterbotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::teeterbot_gazebo::NudgeTeeterbotResponse> should match 
// service_traits::MD5Sum< ::teeterbot_gazebo::NudgeTeeterbot > 
template<>
struct MD5Sum< ::teeterbot_gazebo::NudgeTeeterbotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::teeterbot_gazebo::NudgeTeeterbot >::value();
  }
  static const char* value(const ::teeterbot_gazebo::NudgeTeeterbotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::teeterbot_gazebo::NudgeTeeterbotResponse> should match 
// service_traits::DataType< ::teeterbot_gazebo::NudgeTeeterbot > 
template<>
struct DataType< ::teeterbot_gazebo::NudgeTeeterbotResponse>
{
  static const char* value()
  {
    return DataType< ::teeterbot_gazebo::NudgeTeeterbot >::value();
  }
  static const char* value(const ::teeterbot_gazebo::NudgeTeeterbotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEETERBOT_GAZEBO_MESSAGE_NUDGETEETERBOT_H
