// Generated by gencpp from file teeterbot_gazebo/NudgeTeeterbotResponse.msg
// DO NOT EDIT!


#ifndef TEETERBOT_GAZEBO_MESSAGE_NUDGETEETERBOTRESPONSE_H
#define TEETERBOT_GAZEBO_MESSAGE_NUDGETEETERBOTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace teeterbot_gazebo
{
template <class ContainerAllocator>
struct NudgeTeeterbotResponse_
{
  typedef NudgeTeeterbotResponse_<ContainerAllocator> Type;

  NudgeTeeterbotResponse_()
    {
    }
  NudgeTeeterbotResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::teeterbot_gazebo::NudgeTeeterbotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::teeterbot_gazebo::NudgeTeeterbotResponse_<ContainerAllocator> const> ConstPtr;

}; // struct NudgeTeeterbotResponse_

typedef ::teeterbot_gazebo::NudgeTeeterbotResponse_<std::allocator<void> > NudgeTeeterbotResponse;

typedef boost::shared_ptr< ::teeterbot_gazebo::NudgeTeeterbotResponse > NudgeTeeterbotResponsePtr;
typedef boost::shared_ptr< ::teeterbot_gazebo::NudgeTeeterbotResponse const> NudgeTeeterbotResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::teeterbot_gazebo::NudgeTeeterbotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::teeterbot_gazebo::NudgeTeeterbotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace teeterbot_gazebo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::teeterbot_gazebo::NudgeTeeterbotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teeterbot_gazebo::NudgeTeeterbotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::teeterbot_gazebo::NudgeTeeterbotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::teeterbot_gazebo::NudgeTeeterbotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teeterbot_gazebo::NudgeTeeterbotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teeterbot_gazebo::NudgeTeeterbotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::teeterbot_gazebo::NudgeTeeterbotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::teeterbot_gazebo::NudgeTeeterbotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::teeterbot_gazebo::NudgeTeeterbotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "teeterbot_gazebo/NudgeTeeterbotResponse";
  }

  static const char* value(const ::teeterbot_gazebo::NudgeTeeterbotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::teeterbot_gazebo::NudgeTeeterbotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::teeterbot_gazebo::NudgeTeeterbotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::teeterbot_gazebo::NudgeTeeterbotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NudgeTeeterbotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::teeterbot_gazebo::NudgeTeeterbotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::teeterbot_gazebo::NudgeTeeterbotResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TEETERBOT_GAZEBO_MESSAGE_NUDGETEETERBOTRESPONSE_H
