// Generated by gencpp from file teeterbot_gazebo/NudgeTeeterbotRequest.msg
// DO NOT EDIT!


#ifndef TEETERBOT_GAZEBO_MESSAGE_NUDGETEETERBOTREQUEST_H
#define TEETERBOT_GAZEBO_MESSAGE_NUDGETEETERBOTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace teeterbot_gazebo
{
template <class ContainerAllocator>
struct NudgeTeeterbotRequest_
{
  typedef NudgeTeeterbotRequest_<ContainerAllocator> Type;

  NudgeTeeterbotRequest_()
    : force(0.0)
    , duration(0.0)  {
    }
  NudgeTeeterbotRequest_(const ContainerAllocator& _alloc)
    : force(0.0)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef double _force_type;
  _force_type force;

   typedef double _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::teeterbot_gazebo::NudgeTeeterbotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::teeterbot_gazebo::NudgeTeeterbotRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NudgeTeeterbotRequest_

typedef ::teeterbot_gazebo::NudgeTeeterbotRequest_<std::allocator<void> > NudgeTeeterbotRequest;

typedef boost::shared_ptr< ::teeterbot_gazebo::NudgeTeeterbotRequest > NudgeTeeterbotRequestPtr;
typedef boost::shared_ptr< ::teeterbot_gazebo::NudgeTeeterbotRequest const> NudgeTeeterbotRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::teeterbot_gazebo::NudgeTeeterbotRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::teeterbot_gazebo::NudgeTeeterbotRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace teeterbot_gazebo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::teeterbot_gazebo::NudgeTeeterbotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teeterbot_gazebo::NudgeTeeterbotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::teeterbot_gazebo::NudgeTeeterbotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::teeterbot_gazebo::NudgeTeeterbotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teeterbot_gazebo::NudgeTeeterbotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teeterbot_gazebo::NudgeTeeterbotRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::teeterbot_gazebo::NudgeTeeterbotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "796f52ca95c2168aa4980dc41c6edf7e";
  }

  static const char* value(const ::teeterbot_gazebo::NudgeTeeterbotRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x796f52ca95c2168aULL;
  static const uint64_t static_value2 = 0xa4980dc41c6edf7eULL;
};

template<class ContainerAllocator>
struct DataType< ::teeterbot_gazebo::NudgeTeeterbotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "teeterbot_gazebo/NudgeTeeterbotRequest";
  }

  static const char* value(const ::teeterbot_gazebo::NudgeTeeterbotRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::teeterbot_gazebo::NudgeTeeterbotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 force\n\
float64 duration\n\
";
  }

  static const char* value(const ::teeterbot_gazebo::NudgeTeeterbotRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::teeterbot_gazebo::NudgeTeeterbotRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.force);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NudgeTeeterbotRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::teeterbot_gazebo::NudgeTeeterbotRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::teeterbot_gazebo::NudgeTeeterbotRequest_<ContainerAllocator>& v)
  {
    s << indent << "force: ";
    Printer<double>::stream(s, indent + "  ", v.force);
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEETERBOT_GAZEBO_MESSAGE_NUDGETEETERBOTREQUEST_H
